name: CI to Docker Hub
on:
  push:
    branches: [ master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
 #    - name: Login to Docker Hub
 #       uses: docker/login-action@v1
 #       with:
 #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
 #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn clean package